services:
  elasticnotebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
      - ELASTIC_KERNEL_LOG_LEVEL=${ELASTIC_KERNEL_LOG_LEVEL:-INFO}
      - ELASTIC_KERNEL_SHUTDOWN_SLEEP=0
    volumes:
      - ./.app:/app/
    restart: unless-stopped
    stop_grace_period: 300s
