services:
  elasticnotebook:
    image: ryutarom/elasticnotebook:latest
    ports:
      - "8888:8888"
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
      - ELASTIC_KERNEL_LOG_LEVEL=${ELASTIC_KERNEL_LOG_LEVEL:-INFO}
    volumes:
      - ./.app:/app/
    restart: unless-stopped
