services:
  elasticnotebook:
    image: ryutarom/elasticnotebook:latest
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
    volumes:
      - ./.data:/app/
    restart: unless-stopped
