services:
  elasticnotebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
      - ELASTIC_KERNEL_LOG_LEVEL=${ELASTIC_KERNEL_LOG_LEVEL:-INFO}
    volumes:
      - ./.data:/app/
    restart: unless-stopped
