name: Docker Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check ElasticKernel updates
        id: check
        run: |
          # 現在のコミットハッシュを取得
          git clone https://github.com/MRyutaro/ElasticKernel.git
          cd ElasticKernel
          CURRENT_HASH=$(git rev-parse HEAD)

          # 前回のハッシュを取得（なければ現在のハッシュを使用）
          PREV_HASH=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/elasticnotebook/tags/" | grep -o '"last_updated"' || echo $CURRENT_HASH)

          # ハッシュが異なる場合、更新フラグを立てる
          if [ "$CURRENT_HASH" != "$PREV_HASH" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        if: steps.check.outputs.update_needed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: |
          github.event_name == 'push' ||
          steps.check.outputs.elastic_kernel_updated == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/elasticnotebook:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/elasticnotebook:${{ github.sha }}
          # 単一プラットフォームのみを明示的に指定
          platforms: linux/amd64
          # 余分な機能を無効化
          provenance: false
          sbom: false
